export {
  BOOK_ASSIST_TRANSPORTERS as BOOK_FISH_TRANSPORTERS,
  BOOK_ASSIST_FEES as BOOK_FISH_FEES,
  FISH_VAN_PARKS,
  MOCK_WALLET_BALANCE,
  PORT_TERMINALS_BY_ZONE,
  formatAssistNaira as formatBookFishNaira,
  formatAssistDateLong as formatBookFishDateLong,
  formatAssistDateShort as formatBookFishDateShort,
  getAssistTrucks as getBookFishTrucks,
  getAssistDrivers as getBookFishDrivers,
  type TerminalZone,
  type BookAssistTransporter as BookFishTransporter,
  type BookAssistTruckOption as BookFishTruckOption,
  type BookAssistDriverOption as BookFishDriverOption,
} from "@/lib/book-assist-mock-data";
