import type { Facility, FacilitySummary } from "@/types/facilities.types";

// ─── Bonded Terminals ───
export const MOCK_BONDED_TERMINALS: Facility[] = [
  {
    id: "bt-001",
    name: "Apapa Bonded Terminal A",
    facility_id: "FAC-BT-001",
    category: "BONDED_TERMINAL",
    facility_type: "FACILITY",
    address: "Creek Road, Apapa, Lagos",
    hourly_handling_capacity: 40,
    approved_capacity: 200,
    daily_evacuation_limit: 640,
    operational_status: "ACTIVE",
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2026-04-02T09:30:00Z",
  },
  {
    id: "bt-002",
    name: "Apapa Bonded Terminal B",
    facility_id: "FAC-BT-002",
    category: "BONDED_TERMINAL",
    facility_type: "FACILITY_PREGATE",
    address: "Warehouse Road, Apapa, Lagos",
    hourly_handling_capacity: 30,
    approved_capacity: 150,
    daily_evacuation_limit: 480,
    operational_status: "ACTIVE",
    created_at: "2024-01-20T09:00:00Z",
    updated_at: "2026-03-30T14:15:00Z",
  },
  {
    id: "bt-003",
    name: "Tincan Bonded Terminal",
    facility_id: "FAC-BT-003",
    category: "BONDED_TERMINAL",
    facility_type: "FACILITY",
    address: "Tincan Island Port Complex, Lagos",
    hourly_handling_capacity: 35,
    approved_capacity: 180,
    daily_evacuation_limit: 560,
    operational_status: "ACTIVE",
    created_at: "2024-02-05T08:30:00Z",
    updated_at: "2026-04-14T10:00:00Z",
  },
  {
    id: "bt-004",
    name: "Kirikiri Bonded Holding Bay",
    facility_id: "FAC-BT-004",
    category: "BONDED_TERMINAL",
    facility_type: "FACILITY",
    address: "Kirikiri Industrial Estate, Amuwo-Odofin, Lagos",
    hourly_handling_capacity: 25,
    approved_capacity: 120,
    daily_evacuation_limit: 400,
    operational_status: "INACTIVE",
    created_at: "2024-03-01T09:00:00Z",
    updated_at: "2026-01-20T12:00:00Z",
  },
  {
    id: "bt-005",
    name: "Mile 2 Bonded Terminal",
    facility_id: "FAC-BT-005",
    category: "BONDED_TERMINAL",
    facility_type: "FACILITY_PREGATE",
    address: "Mile 2 Interchange, Amuwo-Odofin, Lagos",
    hourly_handling_capacity: 20,
    approved_capacity: 100,
    daily_evacuation_limit: 320,
    operational_status: "ACTIVE",
    created_at: "2024-04-10T09:00:00Z",
    updated_at: "2026-04-22T11:00:00Z",
  },
  {
    id: "bt-006",
    name: "Maza Maza Bonded Yard",
    facility_id: "FAC-BT-006",
    category: "BONDED_TERMINAL",
    facility_type: "FACILITY",
    address: "Maza Maza, Ajeromi-Ifelodun, Lagos",
    hourly_handling_capacity: 22,
    approved_capacity: 110,
    daily_evacuation_limit: 352,
    operational_status: "ACTIVE",
    created_at: "2024-05-15T08:00:00Z",
    updated_at: "2026-04-20T15:30:00Z",
  },
  {
    id: "bt-007",
    name: "Orile Bonded Holding Bay",
    facility_id: "FAC-BT-007",
    category: "BONDED_TERMINAL",
    facility_type: "FACILITY",
    address: "Orile-Iganmu Industrial Area, Lagos",
    hourly_handling_capacity: 15,
    approved_capacity: 80,
    daily_evacuation_limit: 240,
    operational_status: "ARCHIVED",
    created_at: "2024-06-01T09:00:00Z",
    updated_at: "2025-10-01T10:00:00Z",
  },
];

// ─── Truck Parks ───
export const MOCK_TRUCK_PARKS: Facility[] = [
  {
    id: "tp-001",
    name: "Apapa Truck Park A",
    facility_id: "FAC-TP-001",
    category: "TRUCK_PARK",
    facility_type: "FACILITY",
    address: "Marine Road, Apapa, Lagos",
    hourly_handling_capacity: 60,
    approved_capacity: 120,
    daily_evacuation_limit: 960,
    operational_status: "ACTIVE",
    created_at: "2024-01-12T08:00:00Z",
    updated_at: "2026-04-10T09:00:00Z",
  },
  {
    id: "tp-002",
    name: "Apapa Truck Park B",
    facility_id: "FAC-TP-002",
    category: "TRUCK_PARK",
    facility_type: "FACILITY_PREGATE",
    address: "Old Creek Road, Apapa, Lagos",
    hourly_handling_capacity: 45,
    approved_capacity: 90,
    daily_evacuation_limit: 720,
    operational_status: "ACTIVE",
    created_at: "2024-01-25T09:00:00Z",
    updated_at: "2026-04-18T11:00:00Z",
  },
  {
    id: "tp-003",
    name: "Tincan Truck Park",
    facility_id: "FAC-TP-003",
    category: "TRUCK_PARK",
    facility_type: "FACILITY",
    address: "Tincan Island Port Road, Lagos",
    hourly_handling_capacity: 50,
    approved_capacity: 100,
    daily_evacuation_limit: 800,
    operational_status: "ACTIVE",
    created_at: "2024-02-10T10:00:00Z",
    updated_at: "2026-04-14T15:00:00Z",
  },
  {
    id: "tp-004",
    name: "Kirikiri Truck Park",
    facility_id: "FAC-TP-004",
    category: "TRUCK_PARK",
    facility_type: "FACILITY",
    address: "Kirikiri Road, Amuwo-Odofin, Lagos",
    hourly_handling_capacity: 35,
    approved_capacity: 70,
    daily_evacuation_limit: 560,
    operational_status: "ACTIVE",
    created_at: "2024-03-05T08:30:00Z",
    updated_at: "2026-04-05T14:00:00Z",
  },
  {
    id: "tp-005",
    name: "Mile 2 Truck Park",
    facility_id: "FAC-TP-005",
    category: "TRUCK_PARK",
    facility_type: "FACILITY_PREGATE",
    address: "Mile 2, Amuwo-Odofin, Lagos",
    hourly_handling_capacity: 30,
    approved_capacity: 60,
    daily_evacuation_limit: 480,
    operational_status: "INACTIVE",
    created_at: "2024-04-01T09:00:00Z",
    updated_at: "2026-02-01T10:00:00Z",
  },
  {
    id: "tp-006",
    name: "Orile Truck Terminal",
    facility_id: "FAC-TP-006",
    category: "TRUCK_PARK",
    facility_type: "FACILITY",
    address: "Orile-Iganmu, Lagos",
    hourly_handling_capacity: 25,
    approved_capacity: 50,
    daily_evacuation_limit: 400,
    operational_status: "ACTIVE",
    created_at: "2024-04-20T09:00:00Z",
    updated_at: "2026-04-25T16:00:00Z",
  },
  {
    id: "tp-007",
    name: "Oshodi Truck Terminal",
    facility_id: "FAC-TP-007",
    category: "TRUCK_PARK",
    facility_type: "FACILITY",
    address: "Oshodi Industrial Area, Lagos",
    hourly_handling_capacity: 20,
    approved_capacity: 40,
    daily_evacuation_limit: 320,
    operational_status: "ACTIVE",
    created_at: "2024-05-10T08:00:00Z",
    updated_at: "2026-04-20T13:00:00Z",
  },
  {
    id: "tp-008",
    name: "Maza Maza Truck Park",
    facility_id: "FAC-TP-008",
    category: "TRUCK_PARK",
    facility_type: "FACILITY_PREGATE",
    address: "Maza Maza, Ajeromi-Ifelodun, Lagos",
    hourly_handling_capacity: 28,
    approved_capacity: 55,
    daily_evacuation_limit: 448,
    operational_status: "ACTIVE",
    created_at: "2024-06-01T09:00:00Z",
    updated_at: "2026-04-22T10:30:00Z",
  },
];

// ─── Fish-Van Parks ───
export const MOCK_FISH_VAN_PARKS: Facility[] = [
  {
    id: "fv-001",
    name: "Apapa Fish-Van Park A",
    facility_id: "FAC-FV-001",
    category: "FISH_VAN_PARK",
    facility_type: "FACILITY",
    address: "Fish Market Road, Apapa, Lagos",
    hourly_handling_capacity: 30,
    approved_capacity: 60,
    daily_evacuation_limit: 480,
    operational_status: "ACTIVE",
    created_at: "2024-01-15T08:00:00Z",
    updated_at: "2026-04-01T09:30:00Z",
  },
  {
    id: "fv-002",
    name: "Apapa Fish-Van Park B",
    facility_id: "FAC-FV-002",
    category: "FISH_VAN_PARK",
    facility_type: "FACILITY_PREGATE",
    address: "Ijora Causeway, Apapa, Lagos",
    hourly_handling_capacity: 22,
    approved_capacity: 45,
    daily_evacuation_limit: 352,
    operational_status: "ACTIVE",
    created_at: "2024-02-01T09:00:00Z",
    updated_at: "2026-03-28T14:15:00Z",
  },
  {
    id: "fv-003",
    name: "Tincan Fish-Van Park",
    facility_id: "FAC-FV-003",
    category: "FISH_VAN_PARK",
    facility_type: "FACILITY",
    address: "Tincan Island Road, Lagos",
    hourly_handling_capacity: 25,
    approved_capacity: 50,
    daily_evacuation_limit: 400,
    operational_status: "ACTIVE",
    created_at: "2024-02-20T10:00:00Z",
    updated_at: "2026-04-12T10:00:00Z",
  },
  {
    id: "fv-004",
    name: "Mile 2 Fish-Van Park",
    facility_id: "FAC-FV-004",
    category: "FISH_VAN_PARK",
    facility_type: "FACILITY",
    address: "Mile 2, Amuwo-Odofin, Lagos",
    hourly_handling_capacity: 18,
    approved_capacity: 35,
    daily_evacuation_limit: 288,
    operational_status: "ACTIVE",
    created_at: "2024-03-10T09:00:00Z",
    updated_at: "2026-03-15T16:45:00Z",
  },
  {
    id: "fv-005",
    name: "Oshodi Fish-Van Park",
    facility_id: "FAC-FV-005",
    category: "FISH_VAN_PARK",
    facility_type: "FACILITY_PREGATE",
    address: "Oshodi Market Area, Lagos",
    hourly_handling_capacity: 15,
    approved_capacity: 30,
    daily_evacuation_limit: 240,
    operational_status: "INACTIVE",
    created_at: "2024-04-01T08:00:00Z",
    updated_at: "2026-01-20T12:00:00Z",
  },
  {
    id: "fv-006",
    name: "Orile Fish-Van Park",
    facility_id: "FAC-FV-006",
    category: "FISH_VAN_PARK",
    facility_type: "FACILITY",
    address: "Orile-Iganmu, Lagos",
    hourly_handling_capacity: 12,
    approved_capacity: 25,
    daily_evacuation_limit: 192,
    operational_status: "ACTIVE",
    created_at: "2024-05-01T09:00:00Z",
    updated_at: "2026-04-20T13:15:00Z",
  },
];

// ─── Derived Summaries ───
function buildSummary(list: Facility[]): FacilitySummary {
  const total = list.length;
  const enabled = list.filter((f) => f.operational_status === "ACTIVE").length;
  const disabled = list.filter((f) => f.operational_status === "INACTIVE").length;
  const avgHourly =
    total > 0
      ? Math.round(list.reduce((s, f) => s + f.hourly_handling_capacity, 0) / total)
      : 0;
  const totalEvac = list.reduce((s, f) => s + f.daily_evacuation_limit, 0);
  return { total, enabled, disabled, avg_hourly_handling_capacity: avgHourly, total_daily_evacuation_limit: totalEvac };
}

export const bondedSummary: FacilitySummary = buildSummary(MOCK_BONDED_TERMINALS);
export const truckParksSummary: FacilitySummary = buildSummary(MOCK_TRUCK_PARKS);
export const fishVanSummary: FacilitySummary = buildSummary(MOCK_FISH_VAN_PARKS);
