import type { TEP, TEPsSummary, TEPClassification, TEPSource } from "@/types/teps.types";

export const MOCK_TEPS: TEP[] = [
  // ── Empty TDOs (Shipping Lines) ──
  {
    id: "tep-001",
    reference_number: "ETD-2026-001001",
    classification: "EMPTY_TDO",
    source: "SHIPPING_LINE",
    facility_name: "Apapa Port Complex",
    company_name: "Maersk Line Nigeria",
    user_account: "Adunola Bakare (Operations)",
    truck_plate_number: "AAA-423-WA",
    match_status: "MATCHED",
    created_at: "2026-04-01T08:00:00Z",
    expiry_date: "2026-04-08T23:59:59Z",
    status: "EXPIRED",
    matched_trucks: [{ plate_number: "AAA-423-WA", driver_name: "Emeka Okafor", driver_id: "drv-001", match_timestamp: "2026-04-02T10:15:00Z" }],
    activity_log: [
      { event_type: "CREATED",   performed_by: "Adunola Bakare (Maersk)",   timestamp: "2026-04-01T08:00:00Z", details: "TEP created via bulk upload" },
      { event_type: "VALIDATED", performed_by: "System",                    timestamp: "2026-04-01T08:01:00Z", details: "TEP reference number validated" },
      { event_type: "MATCHED",   performed_by: "System",                    timestamp: "2026-04-02T10:15:00Z", details: "Truck AAA-423-WA matched to TEP" },
      { event_type: "EXPIRED",   performed_by: "System",                    timestamp: "2026-04-09T00:00:00Z", details: "TEP expired automatically" },
    ],
  },
  {
    id: "tep-002",
    reference_number: "ETD-2026-001002",
    classification: "EMPTY_TDO",
    source: "SHIPPING_LINE",
    facility_name: "Tin-Can Island Port",
    company_name: "MSC Shipping Nigeria",
    user_account: "Chibuike Okoye (Ops Manager)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-04-10T09:00:00Z",
    expiry_date: "2026-04-17T23:59:59Z",
    status: "ACTIVE",
    activity_log: [
      { event_type: "CREATED",   performed_by: "Chibuike Okoye (MSC)",   timestamp: "2026-04-10T09:00:00Z", details: "TEP created" },
      { event_type: "VALIDATED", performed_by: "System",                  timestamp: "2026-04-10T09:01:00Z", details: "Validation passed" },
    ],
  },
  {
    id: "tep-003",
    reference_number: "ETD-2026-001003",
    classification: "EMPTY_TDO",
    source: "SHIPPING_LINE",
    facility_name: "Apapa Port Complex",
    company_name: "Hapag-Lloyd Nigeria",
    user_account: "Femi Adebayo (Document Clerk)",
    truck_plate_number: "MN-144-OD",
    match_status: "MATCHED",
    created_at: "2026-04-12T08:30:00Z",
    expiry_date: "2026-04-19T23:59:59Z",
    status: "ACTIVE",
    matched_trucks: [{ plate_number: "MN-144-OD", driver_name: "Sule Musa", driver_id: "drv-002", match_timestamp: "2026-04-13T07:45:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Femi Adebayo (Hapag-Lloyd)", timestamp: "2026-04-12T08:30:00Z", details: "TEP created" },
      { event_type: "MATCHED", performed_by: "System",                     timestamp: "2026-04-13T07:45:00Z", details: "Truck MN-144-OD matched" },
    ],
  },
  {
    id: "tep-004",
    reference_number: "ETD-2026-001004",
    classification: "EMPTY_TDO",
    source: "SHIPPING_LINE",
    facility_name: "Tin-Can Island Port",
    company_name: "CMA CGM Nigeria",
    user_account: "Nneka Obi (Shipping Clerk)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-04-15T10:00:00Z",
    expiry_date: "2026-04-22T23:59:59Z",
    status: "ACTIVE",
    activity_log: [
      { event_type: "CREATED", performed_by: "Nneka Obi (CMA CGM)", timestamp: "2026-04-15T10:00:00Z", details: "TEP created" },
    ],
  },
  {
    id: "tep-005",
    reference_number: "ETD-2026-001005",
    classification: "EMPTY_TDO",
    source: "SHIPPING_LINE",
    facility_name: "Apapa Port Complex",
    company_name: "Maersk Line Nigeria",
    user_account: "Adunola Bakare (Operations)",
    truck_plate_number: "EKO-555-BK",
    match_status: "MATCHED",
    created_at: "2026-03-20T08:00:00Z",
    expiry_date: "2026-03-27T23:59:59Z",
    status: "REVOKED",
    matched_trucks: [{ plate_number: "EKO-555-BK", driver_name: "Ibrahim Aliyu", driver_id: "drv-006", match_timestamp: "2026-03-21T09:00:00Z" }],
    activity_log: [
      { event_type: "CREATED",  performed_by: "Adunola Bakare (Maersk)", timestamp: "2026-03-20T08:00:00Z", details: "TEP created" },
      { event_type: "MATCHED",  performed_by: "System",                   timestamp: "2026-03-21T09:00:00Z", details: "Truck EKO-555-BK matched" },
      { event_type: "REVOKED",  performed_by: "SuperAdmin — Adewale Peters (SA-001)", timestamp: "2026-03-23T14:30:00Z", details: "Revoked — duplicate entry detected" },
    ],
  },
  {
    id: "tep-006",
    reference_number: "ETD-2026-001006",
    classification: "EMPTY_TDO",
    source: "SHIPPING_LINE",
    facility_name: "Tin-Can Island Port",
    company_name: "Evergreen Marine Nigeria",
    user_account: "Seun Afolabi (Port Ops)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-04-18T11:00:00Z",
    expiry_date: "2026-04-25T23:59:59Z",
    status: "ACTIVE",
    activity_log: [
      { event_type: "CREATED", performed_by: "Seun Afolabi (Evergreen)", timestamp: "2026-04-18T11:00:00Z", details: "TEP created" },
    ],
  },
  {
    id: "tep-007",
    reference_number: "ETD-2026-001007",
    classification: "EMPTY_TDO",
    source: "SHIPPING_LINE",
    facility_name: "Apapa Port Complex",
    company_name: "MSC Shipping Nigeria",
    user_account: "Chibuike Okoye (Ops Manager)",
    truck_plate_number: "OGS-789-LA",
    match_status: "MATCHED",
    created_at: "2026-04-20T09:00:00Z",
    expiry_date: "2026-04-27T23:59:59Z",
    status: "ACTIVE",
    matched_trucks: [{ plate_number: "OGS-789-LA", driver_name: "Fatima Yusuf", driver_id: "drv-005", match_timestamp: "2026-04-20T15:30:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Chibuike Okoye (MSC)",  timestamp: "2026-04-20T09:00:00Z", details: "TEP created" },
      { event_type: "MATCHED", performed_by: "System",                 timestamp: "2026-04-20T15:30:00Z", details: "Truck OGS-789-LA matched" },
    ],
  },

  // ── Import TDOs (Port Terminals) ──
  {
    id: "tep-008",
    reference_number: "ITD-2026-002001",
    classification: "IMPORT_TDO",
    source: "PORT_TERMINAL",
    facility_name: "APM Terminals Apapa",
    company_name: "Dangote Transport Services",
    user_account: "Bola Afolabi (Terminal Ops)",
    truck_plate_number: "LND-501-KJ",
    match_status: "MATCHED",
    created_at: "2026-04-05T08:00:00Z",
    expiry_date: "2026-04-12T23:59:59Z",
    status: "EXPIRED",
    matched_trucks: [{ plate_number: "LND-501-KJ", driver_name: "Amina Bello", driver_id: "drv-003", match_timestamp: "2026-04-06T06:45:00Z" }],
    activity_log: [
      { event_type: "CREATED",   performed_by: "Bola Afolabi (APM Terminals)", timestamp: "2026-04-05T08:00:00Z", details: "TEP created for import consignment" },
      { event_type: "MATCHED",   performed_by: "System",                        timestamp: "2026-04-06T06:45:00Z", details: "Truck LND-501-KJ matched" },
      { event_type: "EXPIRED",   performed_by: "System",                        timestamp: "2026-04-13T00:00:00Z", details: "TEP expired automatically" },
    ],
  },
  {
    id: "tep-009",
    reference_number: "ITD-2026-002002",
    classification: "IMPORT_TDO",
    source: "PORT_TERMINAL",
    facility_name: "Tin-Can Island Terminal",
    company_name: "BUA Transport Services",
    user_account: "Yetunde Adeola (Gate Control)",
    truck_plate_number: "ABJ-872-FG",
    match_status: "MATCHED",
    created_at: "2026-04-15T09:30:00Z",
    expiry_date: "2026-04-22T23:59:59Z",
    status: "ACTIVE",
    matched_trucks: [{ plate_number: "ABJ-872-FG", driver_name: "Chukwudi Eze", driver_id: "drv-004", match_timestamp: "2026-04-15T14:20:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Yetunde Adeola (Tin-Can)", timestamp: "2026-04-15T09:30:00Z", details: "TEP created" },
      { event_type: "MATCHED", performed_by: "System",                    timestamp: "2026-04-15T14:20:00Z", details: "Truck ABJ-872-FG matched" },
    ],
  },
  {
    id: "tep-010",
    reference_number: "ITD-2026-002003",
    classification: "IMPORT_TDO",
    source: "PORT_TERMINAL",
    facility_name: "APM Terminals Apapa",
    company_name: "Spedag Intermodal Nigeria",
    user_account: "Fola Kuti (Operations)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-04-18T10:00:00Z",
    expiry_date: "2026-04-25T23:59:59Z",
    status: "ACTIVE",
    activity_log: [
      { event_type: "CREATED", performed_by: "Fola Kuti (APM Terminals)", timestamp: "2026-04-18T10:00:00Z", details: "TEP created for import load" },
    ],
  },
  {
    id: "tep-011",
    reference_number: "ITD-2026-002004",
    classification: "IMPORT_TDO",
    source: "PORT_TERMINAL",
    facility_name: "Tin-Can Island Terminal",
    company_name: "Coscharis Transport",
    user_account: "Emeka Okafor (Logistics)",
    truck_plate_number: "RIV-944-PH",
    match_status: "MATCHED",
    created_at: "2026-04-20T08:00:00Z",
    expiry_date: "2026-04-27T23:59:59Z",
    status: "ACTIVE",
    matched_trucks: [{ plate_number: "RIV-944-PH", driver_name: "Ngozi Okonkwo", driver_id: "drv-007", match_timestamp: "2026-04-20T11:00:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Emeka Okafor (Coscharis)", timestamp: "2026-04-20T08:00:00Z", details: "TEP created" },
      { event_type: "MATCHED", performed_by: "System",                    timestamp: "2026-04-20T11:00:00Z", details: "Truck RIV-944-PH matched" },
    ],
  },
  {
    id: "tep-012",
    reference_number: "ITD-2026-002005",
    classification: "IMPORT_TDO",
    source: "PORT_TERMINAL",
    facility_name: "APM Terminals Apapa",
    company_name: "Mikano Logistics",
    user_account: "Tunde Fashola (Gate Officer)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-04-22T09:00:00Z",
    expiry_date: "2026-04-29T23:59:59Z",
    status: "ACTIVE",
    activity_log: [
      { event_type: "CREATED", performed_by: "Tunde Fashola (APM)", timestamp: "2026-04-22T09:00:00Z", details: "TEP created" },
    ],
  },
  {
    id: "tep-013",
    reference_number: "ITD-2026-002006",
    classification: "IMPORT_TDO",
    source: "PORT_TERMINAL",
    facility_name: "Tin-Can Island Terminal",
    company_name: "Dangote Transport Services",
    user_account: "Yetunde Adeola (Gate Control)",
    truck_plate_number: "KAN-256-NA",
    match_status: "MATCHED",
    created_at: "2026-03-28T08:00:00Z",
    expiry_date: "2026-04-04T23:59:59Z",
    status: "REVOKED",
    matched_trucks: [{ plate_number: "KAN-256-NA", driver_name: "Usman Bello", driver_id: "drv-010", match_timestamp: "2026-03-29T08:30:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Yetunde Adeola (Tin-Can)", timestamp: "2026-03-28T08:00:00Z", details: "TEP created" },
      { event_type: "MATCHED", performed_by: "System",                    timestamp: "2026-03-29T08:30:00Z", details: "Truck KAN-256-NA matched" },
      { event_type: "REVOKED", performed_by: "SuperAdmin — Adewale Peters (SA-001)", timestamp: "2026-03-30T16:00:00Z", details: "Revoked — consignment cancelled by importer" },
    ],
  },
  {
    id: "tep-014",
    reference_number: "ITD-2026-002007",
    classification: "IMPORT_TDO",
    source: "PORT_TERMINAL",
    facility_name: "APM Terminals Apapa",
    company_name: "ABC Logistics Ltd",
    user_account: "Fola Kuti (Operations)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-04-24T10:00:00Z",
    expiry_date: "2026-05-01T23:59:59Z",
    status: "ACTIVE",
    activity_log: [
      { event_type: "CREATED", performed_by: "Fola Kuti (APM Terminals)", timestamp: "2026-04-24T10:00:00Z", details: "TEP created" },
    ],
  },

  // ── Export TDOs (EPTs) ──
  {
    id: "tep-015",
    reference_number: "XTD-2026-003001",
    classification: "EXPORT_TDO",
    source: "EPT",
    facility_name: "Apapa EPT 1",
    company_name: "BUA Transport Services",
    user_account: "Ike Onwuegbu (Export Ops)",
    truck_plate_number: "LAG-777-AA",
    match_status: "MATCHED",
    created_at: "2026-04-08T08:00:00Z",
    expiry_date: "2026-04-15T23:59:59Z",
    status: "EXPIRED",
    matched_trucks: [{ plate_number: "LAG-777-AA", driver_name: "Adewale Peters", driver_id: "drv-008", match_timestamp: "2026-04-08T14:00:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Ike Onwuegbu (EPT)",  timestamp: "2026-04-08T08:00:00Z", details: "Export TDO created for outbound cargo" },
      { event_type: "MATCHED", performed_by: "System",               timestamp: "2026-04-08T14:00:00Z", details: "Truck LAG-777-AA matched" },
      { event_type: "EXPIRED", performed_by: "System",               timestamp: "2026-04-16T00:00:00Z", details: "TEP expired" },
    ],
  },
  {
    id: "tep-016",
    reference_number: "XTD-2026-003002",
    classification: "EXPORT_TDO",
    source: "EPT",
    facility_name: "Tincan EPT 2",
    company_name: "Coscharis Transport",
    user_account: "Bisi Adekunle (Logistics)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-04-17T09:30:00Z",
    expiry_date: "2026-04-24T23:59:59Z",
    status: "ACTIVE",
    activity_log: [
      { event_type: "CREATED", performed_by: "Bisi Adekunle (EPT)", timestamp: "2026-04-17T09:30:00Z", details: "Export TDO created" },
    ],
  },
  {
    id: "tep-017",
    reference_number: "XTD-2026-003003",
    classification: "EXPORT_TDO",
    source: "EPT",
    facility_name: "Apapa EPT 1",
    company_name: "Mikano Logistics",
    user_account: "Ike Onwuegbu (Export Ops)",
    truck_plate_number: "IMO-312-ZD",
    match_status: "MATCHED",
    created_at: "2026-04-19T10:00:00Z",
    expiry_date: "2026-04-26T23:59:59Z",
    status: "ACTIVE",
    matched_trucks: [{ plate_number: "IMO-312-ZD", driver_name: "Kemi Adeyemi", driver_id: "drv-009", match_timestamp: "2026-04-19T16:10:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Ike Onwuegbu (EPT)", timestamp: "2026-04-19T10:00:00Z", details: "Export TDO created" },
      { event_type: "MATCHED", performed_by: "System",               timestamp: "2026-04-19T16:10:00Z", details: "Truck IMO-312-ZD matched" },
    ],
  },
  {
    id: "tep-018",
    reference_number: "XTD-2026-003004",
    classification: "EXPORT_TDO",
    source: "EPT",
    facility_name: "Tincan EPT 2",
    company_name: "Spedag Intermodal Nigeria",
    user_account: "Bisi Adekunle (Logistics)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-04-21T08:30:00Z",
    expiry_date: "2026-04-28T23:59:59Z",
    status: "ACTIVE",
    activity_log: [
      { event_type: "CREATED", performed_by: "Bisi Adekunle (EPT)", timestamp: "2026-04-21T08:30:00Z", details: "Export TDO created" },
    ],
  },
  {
    id: "tep-019",
    reference_number: "XTD-2026-003005",
    classification: "EXPORT_TDO",
    source: "EPT",
    facility_name: "Apapa EPT 1",
    company_name: "ABC Logistics Ltd",
    user_account: "Ike Onwuegbu (Export Ops)",
    truck_plate_number: "ABJ-872-FG",
    match_status: "MATCHED",
    created_at: "2026-04-23T09:00:00Z",
    expiry_date: "2026-04-30T23:59:59Z",
    status: "ACTIVE",
    matched_trucks: [{ plate_number: "ABJ-872-FG", driver_name: "Chukwudi Eze", driver_id: "drv-004", match_timestamp: "2026-04-23T11:30:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Ike Onwuegbu (EPT)", timestamp: "2026-04-23T09:00:00Z", details: "Export TDO created" },
      { event_type: "MATCHED", performed_by: "System",               timestamp: "2026-04-23T11:30:00Z", details: "Truck ABJ-872-FG matched" },
    ],
  },
  {
    id: "tep-020",
    reference_number: "XTD-2026-003006",
    classification: "EXPORT_TDO",
    source: "EPT",
    facility_name: "Tincan EPT 2",
    company_name: "Dangote Transport Services",
    user_account: "Bisi Adekunle (Logistics)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-03-15T10:00:00Z",
    expiry_date: "2026-03-22T23:59:59Z",
    status: "REVOKED",
    activity_log: [
      { event_type: "CREATED", performed_by: "Bisi Adekunle (EPT)", timestamp: "2026-03-15T10:00:00Z", details: "Export TDO created" },
      { event_type: "REVOKED", performed_by: "SuperAdmin — Adewale Peters (SA-001)", timestamp: "2026-03-17T09:00:00Z", details: "Revoked — cargo reassigned to different route" },
    ],
  },

  // ── Gatepass (Port) ──
  {
    id: "tep-021",
    reference_number: "GPP-2026-004001",
    classification: "GATEPASS_PORT",
    source: "PORT_TERMINAL",
    facility_name: "APM Terminals Apapa",
    company_name: "Maersk Line Nigeria",
    user_account: "Bola Afolabi (Terminal Ops)",
    truck_plate_number: "EKO-555-BK",
    match_status: "MATCHED",
    created_at: "2026-04-14T07:00:00Z",
    expiry_date: "2026-04-14T23:59:59Z",
    status: "EXPIRED",
    matched_trucks: [{ plate_number: "EKO-555-BK", driver_name: "Ibrahim Aliyu", driver_id: "drv-006", match_timestamp: "2026-04-14T08:30:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Bola Afolabi (APM Terminals)", timestamp: "2026-04-14T07:00:00Z", details: "Gate pass issued for port entry" },
      { event_type: "MATCHED", performed_by: "System",                        timestamp: "2026-04-14T08:30:00Z", details: "Truck EKO-555-BK matched" },
      { event_type: "EXPIRED", performed_by: "System",                        timestamp: "2026-04-15T00:00:00Z", details: "Daily gatepass expired" },
    ],
  },
  {
    id: "tep-022",
    reference_number: "GPP-2026-004002",
    classification: "GATEPASS_PORT",
    source: "PORT_TERMINAL",
    facility_name: "Tin-Can Island Terminal",
    company_name: "CMA CGM Nigeria",
    user_account: "Yetunde Adeola (Gate Control)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-04-24T06:30:00Z",
    expiry_date: "2026-04-24T23:59:59Z",
    status: "ACTIVE",
    activity_log: [
      { event_type: "CREATED", performed_by: "Yetunde Adeola (Tin-Can)", timestamp: "2026-04-24T06:30:00Z", details: "Gate pass issued" },
    ],
  },
  {
    id: "tep-023",
    reference_number: "GPP-2026-004003",
    classification: "GATEPASS_PORT",
    source: "PORT_TERMINAL",
    facility_name: "APM Terminals Apapa",
    company_name: "BUA Transport Services",
    user_account: "Bola Afolabi (Terminal Ops)",
    truck_plate_number: "KAN-256-NA",
    match_status: "MATCHED",
    created_at: "2026-04-25T07:00:00Z",
    expiry_date: "2026-04-25T23:59:59Z",
    status: "ACTIVE",
    matched_trucks: [{ plate_number: "KAN-256-NA", driver_name: "Usman Bello", driver_id: "drv-010", match_timestamp: "2026-04-25T09:15:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Bola Afolabi (APM)",  timestamp: "2026-04-25T07:00:00Z", details: "Gate pass issued" },
      { event_type: "MATCHED", performed_by: "System",               timestamp: "2026-04-25T09:15:00Z", details: "Truck KAN-256-NA matched" },
    ],
  },
  {
    id: "tep-024",
    reference_number: "GPP-2026-004004",
    classification: "GATEPASS_PORT",
    source: "PORT_TERMINAL",
    facility_name: "Tin-Can Island Terminal",
    company_name: "Dangote Transport Services",
    user_account: "Yetunde Adeola (Gate Control)",
    truck_plate_number: "RIV-944-PH",
    match_status: "MATCHED",
    created_at: "2026-04-26T06:45:00Z",
    expiry_date: "2026-04-26T23:59:59Z",
    status: "ACTIVE",
    matched_trucks: [{ plate_number: "RIV-944-PH", driver_name: "Ngozi Okonkwo", driver_id: "drv-007", match_timestamp: "2026-04-26T08:00:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Yetunde Adeola (Tin-Can)", timestamp: "2026-04-26T06:45:00Z", details: "Gate pass issued" },
      { event_type: "MATCHED", performed_by: "System",                    timestamp: "2026-04-26T08:00:00Z", details: "Truck RIV-944-PH matched" },
    ],
  },
  {
    id: "tep-025",
    reference_number: "GPP-2026-004005",
    classification: "GATEPASS_PORT",
    source: "PORT_TERMINAL",
    facility_name: "APM Terminals Apapa",
    company_name: "MSC Shipping Nigeria",
    user_account: "Bola Afolabi (Terminal Ops)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-04-27T07:00:00Z",
    expiry_date: "2026-04-27T23:59:59Z",
    status: "ACTIVE",
    activity_log: [
      { event_type: "CREATED", performed_by: "Bola Afolabi (APM)", timestamp: "2026-04-27T07:00:00Z", details: "Gate pass issued" },
    ],
  },

  // ── Gatepass (Non-Port) ──
  {
    id: "tep-026",
    reference_number: "GPN-2026-005001",
    classification: "GATEPASS_NON_PORT",
    source: "NON_PORT_TERMINAL",
    facility_name: "Dangote Logistics Corridor",
    company_name: "ABC Logistics Ltd",
    user_account: "Emeka Okafor (Logistics)",
    truck_plate_number: "LND-501-KJ",
    match_status: "MATCHED",
    created_at: "2026-04-16T08:00:00Z",
    expiry_date: "2026-04-16T23:59:59Z",
    status: "EXPIRED",
    matched_trucks: [{ plate_number: "LND-501-KJ", driver_name: "Amina Bello", driver_id: "drv-003", match_timestamp: "2026-04-16T10:00:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Emeka Okafor (ABC Logistics)", timestamp: "2026-04-16T08:00:00Z", details: "Non-port gate pass issued" },
      { event_type: "MATCHED", performed_by: "System",                        timestamp: "2026-04-16T10:00:00Z", details: "Truck LND-501-KJ matched" },
      { event_type: "EXPIRED", performed_by: "System",                        timestamp: "2026-04-17T00:00:00Z", details: "Daily gatepass expired" },
    ],
  },
  {
    id: "tep-027",
    reference_number: "GPN-2026-005002",
    classification: "GATEPASS_NON_PORT",
    source: "NON_PORT_TERMINAL",
    facility_name: "Apapa Bonded Terminal A",
    company_name: "Mikano Logistics",
    user_account: "Tunde Fashola (Gate Officer)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-04-22T07:30:00Z",
    expiry_date: "2026-04-22T23:59:59Z",
    status: "ACTIVE",
    activity_log: [
      { event_type: "CREATED", performed_by: "Tunde Fashola (Bonded Terminal)", timestamp: "2026-04-22T07:30:00Z", details: "Non-port gate pass issued" },
    ],
  },
  {
    id: "tep-028",
    reference_number: "GPN-2026-005003",
    classification: "GATEPASS_NON_PORT",
    source: "NON_PORT_TERMINAL",
    facility_name: "Creek Road Bonded Terminal",
    company_name: "Coscharis Transport",
    user_account: "Bisi Adekunle (Logistics)",
    truck_plate_number: "MN-144-OD",
    match_status: "MATCHED",
    created_at: "2026-04-25T07:00:00Z",
    expiry_date: "2026-04-25T23:59:59Z",
    status: "ACTIVE",
    matched_trucks: [{ plate_number: "MN-144-OD", driver_name: "Sule Musa", driver_id: "drv-002", match_timestamp: "2026-04-25T09:45:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Bisi Adekunle (Creek Road)", timestamp: "2026-04-25T07:00:00Z", details: "Non-port gate pass issued" },
      { event_type: "MATCHED", performed_by: "System",                      timestamp: "2026-04-25T09:45:00Z", details: "Truck MN-144-OD matched" },
    ],
  },
  {
    id: "tep-029",
    reference_number: "GPN-2026-005004",
    classification: "GATEPASS_NON_PORT",
    source: "NON_PORT_TERMINAL",
    facility_name: "Dangote Logistics Corridor",
    company_name: "Spedag Intermodal Nigeria",
    user_account: "Emeka Okafor (Logistics)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-04-26T08:00:00Z",
    expiry_date: "2026-04-26T23:59:59Z",
    status: "ACTIVE",
    activity_log: [
      { event_type: "CREATED", performed_by: "Emeka Okafor (ABC Logistics)", timestamp: "2026-04-26T08:00:00Z", details: "Non-port gate pass issued" },
    ],
  },
  {
    id: "tep-030",
    reference_number: "GPN-2026-005005",
    classification: "GATEPASS_NON_PORT",
    source: "NON_PORT_TERMINAL",
    facility_name: "Apapa Bonded Terminal A",
    company_name: "BUA Transport Services",
    user_account: "Tunde Fashola (Gate Officer)",
    truck_plate_number: "AAA-423-WA",
    match_status: "MATCHED",
    created_at: "2026-04-10T07:30:00Z",
    expiry_date: "2026-04-10T23:59:59Z",
    status: "REVOKED",
    matched_trucks: [{ plate_number: "AAA-423-WA", driver_name: "Emeka Okafor", driver_id: "drv-001", match_timestamp: "2026-04-10T09:00:00Z" }],
    activity_log: [
      { event_type: "CREATED", performed_by: "Tunde Fashola (Bonded Terminal)", timestamp: "2026-04-10T07:30:00Z", details: "Non-port gate pass issued" },
      { event_type: "MATCHED", performed_by: "System",                           timestamp: "2026-04-10T09:00:00Z", details: "Truck AAA-423-WA matched" },
      { event_type: "REVOKED", performed_by: "SuperAdmin — Adewale Peters (SA-001)", timestamp: "2026-04-10T14:00:00Z", details: "Revoked — truck flagged for route violation" },
    ],
  },
  {
    id: "tep-031",
    reference_number: "GPN-2026-005006",
    classification: "GATEPASS_NON_PORT",
    source: "NON_PORT_TERMINAL",
    facility_name: "Creek Road Bonded Terminal",
    company_name: "Dangote Transport Services",
    user_account: "Bisi Adekunle (Logistics)",
    truck_plate_number: undefined,
    match_status: "UNMATCHED",
    created_at: "2026-04-27T07:00:00Z",
    expiry_date: "2026-04-27T23:59:59Z",
    status: "ACTIVE",
    activity_log: [
      { event_type: "CREATED", performed_by: "Bisi Adekunle (Creek Road)", timestamp: "2026-04-27T07:00:00Z", details: "Non-port gate pass issued" },
    ],
  },
];

// ─── Summary Builder ───
export function buildTEPsSummary(teps: TEP[]): TEPsSummary {
  const countBy = <K extends string>(arr: TEP[], fn: (t: TEP) => K, keys: K[]) =>
    Object.fromEntries(keys.map((k) => [k, arr.filter((t) => fn(t) === k).length])) as Record<K, number>;

  return {
    total:    teps.length,
    active:   teps.filter((t) => t.status === "ACTIVE").length,
    expired:  teps.filter((t) => t.status === "EXPIRED").length,
    revoked:  teps.filter((t) => t.status === "REVOKED").length,
    matched:  teps.filter((t) => t.match_status === "MATCHED").length,
    unmatched: teps.filter((t) => t.match_status === "UNMATCHED").length,
    by_classification: countBy(teps, (t) => t.classification, ["EMPTY_TDO","IMPORT_TDO","EXPORT_TDO","GATEPASS_PORT","GATEPASS_NON_PORT"]),
    by_source: countBy(teps, (t) => t.source, ["SHIPPING_LINE","PORT_TERMINAL","NON_PORT_TERMINAL","EPT"]),
  };
}
