import type { Terminal, TerminalsSummary, TerminalCapacityDataPoint } from "@/types/terminals.types";

// ─── All Terminals ───
export const MOCK_TERMINALS: Terminal[] = [
  // ── Port Terminals — Apapa ──
  {
    id: "t-001",
    terminal_name: "APM Terminals Apapa",
    terminal_type: "PORT_TERMINAL",
    terminal_code: "TRM-APA-001",
    location: "Apapa Port Complex, Marine Road, Lagos",
    port_zone: "APAPA",
    approved_daily_truck_capacity: 800,
    hourly_truck_handling_capacity: 50,
    operational_status: "ACTIVE",
    created_at: "2024-01-15T08:00:00Z",
    updated_at: "2026-04-01T10:30:00Z",
  },
  {
    id: "t-002",
    terminal_name: "PTML Apapa",
    terminal_type: "PORT_TERMINAL",
    terminal_code: "TRM-APA-002",
    location: "Port & Terminal Mgmt Ltd, Apapa, Lagos",
    port_zone: "APAPA",
    approved_daily_truck_capacity: 600,
    hourly_truck_handling_capacity: 38,
    operational_status: "ACTIVE",
    created_at: "2024-02-10T09:00:00Z",
    updated_at: "2026-03-28T14:15:00Z",
  },
  {
    id: "t-003",
    terminal_name: "Grimaldi Terminal Apapa",
    terminal_type: "PORT_TERMINAL",
    terminal_code: "TRM-APA-003",
    location: "Apapa Port, Wharf Road, Lagos",
    port_zone: "APAPA",
    approved_daily_truck_capacity: 450,
    hourly_truck_handling_capacity: 30,
    operational_status: "ACTIVE",
    created_at: "2024-02-20T10:00:00Z",
    updated_at: "2026-04-10T09:00:00Z",
  },
  {
    id: "t-004",
    terminal_name: "ENL Terminal Apapa",
    terminal_type: "PORT_TERMINAL",
    terminal_code: "TRM-APA-004",
    location: "ENL Wharf Road, Apapa, Lagos",
    port_zone: "APAPA",
    approved_daily_truck_capacity: 350,
    hourly_truck_handling_capacity: 22,
    operational_status: "ACTIVE",
    created_at: "2024-03-05T11:00:00Z",
    updated_at: "2026-03-20T16:45:00Z",
  },
  {
    id: "t-005",
    terminal_name: "Josepdam Port Services",
    terminal_type: "PORT_TERMINAL",
    terminal_code: "TRM-APA-005",
    location: "Kirikiri Industrial Estate, Apapa, Lagos",
    port_zone: "APAPA",
    approved_daily_truck_capacity: 300,
    hourly_truck_handling_capacity: 19,
    operational_status: "INACTIVE",
    created_at: "2024-04-01T08:30:00Z",
    updated_at: "2026-01-15T12:00:00Z",
  },
  {
    id: "t-006",
    terminal_name: "Five Star Logistics Terminal",
    terminal_type: "PORT_TERMINAL",
    terminal_code: "TRM-APA-006",
    location: "Creek Road, Apapa, Lagos",
    port_zone: "APAPA",
    approved_daily_truck_capacity: 280,
    hourly_truck_handling_capacity: 18,
    operational_status: "ACTIVE",
    created_at: "2024-05-12T09:00:00Z",
    updated_at: "2026-04-20T11:30:00Z",
  },
  {
    id: "t-007",
    terminal_name: "Lagos Port Complex Terminal",
    terminal_type: "PORT_TERMINAL",
    terminal_code: "TRM-LPC-001",
    location: "Lagos Port Complex, Apapa, Lagos",
    port_zone: "APAPA",
    approved_daily_truck_capacity: 380,
    hourly_truck_handling_capacity: 24,
    operational_status: "ACTIVE",
    created_at: "2024-05-01T09:00:00Z",
    updated_at: "2026-04-25T16:00:00Z",
  },
  // ── Port Terminals — Tincan ──
  {
    id: "t-008",
    terminal_name: "Tincan Island Port Terminal",
    terminal_type: "PORT_TERMINAL",
    terminal_code: "TRM-TIN-001",
    location: "Tincan Island Port, Lagos",
    port_zone: "TINCAN",
    approved_daily_truck_capacity: 700,
    hourly_truck_handling_capacity: 44,
    operational_status: "ACTIVE",
    created_at: "2024-01-20T10:00:00Z",
    updated_at: "2026-04-15T09:00:00Z",
  },
  {
    id: "t-009",
    terminal_name: "Greenview Development Co.",
    terminal_type: "PORT_TERMINAL",
    terminal_code: "TRM-TIN-002",
    location: "Greenview Terminal, Tincan Island, Lagos",
    port_zone: "TINCAN",
    approved_daily_truck_capacity: 400,
    hourly_truck_handling_capacity: 25,
    operational_status: "ACTIVE",
    created_at: "2024-03-01T08:00:00Z",
    updated_at: "2026-04-05T14:00:00Z",
  },
  {
    id: "t-010",
    terminal_name: "Ports & Cargo Ltd",
    terminal_type: "PORT_TERMINAL",
    terminal_code: "TRM-TIN-003",
    location: "Ports & Cargo Complex, Tincan Island, Lagos",
    port_zone: "TINCAN",
    approved_daily_truck_capacity: 320,
    hourly_truck_handling_capacity: 20,
    operational_status: "ACTIVE",
    created_at: "2024-04-15T08:00:00Z",
    updated_at: "2026-03-10T10:00:00Z",
  },
  // ── Non-Port Terminals — Apapa ──
  {
    id: "t-011",
    terminal_name: "Apapa Non-Port Terminal A",
    terminal_type: "NON_PORT_TERMINAL",
    terminal_code: "TRM-NPA-001",
    location: "Oil Mill Street, Apapa, Lagos",
    approved_daily_truck_capacity: 500,
    hourly_truck_handling_capacity: 32,
    operational_status: "ACTIVE",
    created_at: "2024-02-01T09:00:00Z",
    updated_at: "2026-04-12T11:00:00Z",
  },
  {
    id: "t-012",
    terminal_name: "Apapa Non-Port Terminal B",
    terminal_type: "NON_PORT_TERMINAL",
    terminal_code: "TRM-NPA-002",
    location: "Warehouse Road, Apapa, Lagos",
    approved_daily_truck_capacity: 350,
    hourly_truck_handling_capacity: 22,
    operational_status: "ACTIVE",
    created_at: "2024-02-25T10:00:00Z",
    updated_at: "2026-03-30T15:00:00Z",
  },
  {
    id: "t-013",
    terminal_name: "Mile 2 Transit Terminal",
    terminal_type: "NON_PORT_TERMINAL",
    terminal_code: "TRM-NPA-003",
    location: "Mile 2 Bus Stop Area, Amuwo-Odofin, Lagos",
    approved_daily_truck_capacity: 250,
    hourly_truck_handling_capacity: 16,
    operational_status: "INACTIVE",
    created_at: "2024-06-01T09:00:00Z",
    updated_at: "2025-12-01T08:00:00Z",
  },
  // ── Non-Port Terminals — Tincan ──
  {
    id: "t-014",
    terminal_name: "Tincan Non-Port Terminal A",
    terminal_type: "NON_PORT_TERMINAL",
    terminal_code: "TRM-NTP-001",
    location: "Tincan Island, Apapa, Lagos",
    approved_daily_truck_capacity: 420,
    hourly_truck_handling_capacity: 27,
    operational_status: "ACTIVE",
    created_at: "2024-03-10T09:00:00Z",
    updated_at: "2026-04-18T13:00:00Z",
  },
  {
    id: "t-015",
    terminal_name: "Tincan Non-Port Terminal B",
    terminal_type: "NON_PORT_TERMINAL",
    terminal_code: "TRM-NTP-002",
    location: "Tincan Island, Apapa, Lagos",
    approved_daily_truck_capacity: 280,
    hourly_truck_handling_capacity: 18,
    operational_status: "ARCHIVED",
    created_at: "2024-04-20T09:00:00Z",
    updated_at: "2025-11-01T10:00:00Z",
  },
];

// ─── Derived Summary ───
const active = MOCK_TERMINALS.filter((t) => t.operational_status === "ACTIVE").length;
const inactive = MOCK_TERMINALS.filter((t) => t.operational_status === "INACTIVE").length;
const portCount = MOCK_TERMINALS.filter((t) => t.terminal_type === "PORT_TERMINAL").length;
const nonPortCount = MOCK_TERMINALS.filter((t) => t.terminal_type === "NON_PORT_TERMINAL").length;
const avgHourly = Math.round(
  MOCK_TERMINALS.reduce((s, t) => s + t.hourly_truck_handling_capacity, 0) / MOCK_TERMINALS.length
);

export const terminalsSummary: TerminalsSummary = {
  total: MOCK_TERMINALS.length,
  port_terminals: portCount,
  non_port_terminals: nonPortCount,
  enabled: active,
  disabled: inactive,
  avg_hourly_handling_capacity: avgHourly,
};

// ─── Port Terminals Chart Data (Apapa then Tincan axis) ───
export const portTerminalChartData: TerminalCapacityDataPoint[] = [
  { terminal: "APM Apapa",   approved_daily_capacity: 800, dttr: 672, live_booking_count: 745 },
  { terminal: "PTML Apapa",  approved_daily_capacity: 600, dttr: 498, live_booking_count: 560 },
  { terminal: "Grimaldi",    approved_daily_capacity: 450, dttr: 391, live_booking_count: 418 },
  { terminal: "ENL",         approved_daily_capacity: 350, dttr: 304, live_booking_count: 325 },
  { terminal: "5-Star",      approved_daily_capacity: 280, dttr: 245, live_booking_count: 268 },
  { terminal: "Josepdam",    approved_daily_capacity: 300, dttr: 0,   live_booking_count: 0 },
  { terminal: "Lagos PC",    approved_daily_capacity: 380, dttr: 331, live_booking_count: 357 },
  { terminal: "Tincan IP",   approved_daily_capacity: 700, dttr: 589, live_booking_count: 654 },
  { terminal: "Greenview",   approved_daily_capacity: 400, dttr: 345, live_booking_count: 378 },
  { terminal: "P&Cargo",     approved_daily_capacity: 320, dttr: 278, live_booking_count: 302 },
];

// ─── Non-Port Terminals Chart Data (Apapa then Tincan axis) ───
export const nonPortTerminalChartData: TerminalCapacityDataPoint[] = [
  { terminal: "Apapa NP-A",  approved_daily_capacity: 500, dttr: 423, live_booking_count: 467 },
  { terminal: "Apapa NP-B",  approved_daily_capacity: 350, dttr: 298, live_booking_count: 321 },
  { terminal: "Mile 2",      approved_daily_capacity: 250, dttr: 0,   live_booking_count: 0 },
  { terminal: "Tincan NP-A", approved_daily_capacity: 420, dttr: 356, live_booking_count: 389 },
  { terminal: "Tincan NP-B", approved_daily_capacity: 280, dttr: 0,   live_booking_count: 0 },
];
