import type { Truck, TrucksSummary } from "@/types/trucks.types";

// ─── All Trucks (single source of truth) ───
export const MOCK_TRUCKS: Truck[] = [
  // ── MSS Verified ──
  {
    id: "trk-001",
    plate_number: "AAA-423-WA",
    truck_type: "40-FOOTER",
    color: "White",
    chassis_number: "WDB9300341L123456",
    brand: "Mercedes-Benz",
    model: "Actros 2548",
    truck_length: "12.2m",
    truck_capacity: "40 Tons",
    created_at: "2024-02-10T08:00:00Z",
    registration_status: "MSS_VERIFIED",
    registered_by: { company_name: "ABC Logistics Ltd", user_account: "Emeka Okafor" },
    visibility: "PUBLIC",
    truck_status: "AVAILABLE",
    mss_verification_number: "MSS-2024-001234",
    verification_timestamp: "2024-02-15T10:30:00Z",
    rfid_tag_number: "RFID-ETSS-001234",
  },
  {
    id: "trk-002",
    plate_number: "MN-144-OD",
    truck_type: "20-FOOTER",
    color: "Red",
    chassis_number: "WMA06XZZ8NM234567",
    brand: "MAN",
    model: "TGX 26.480",
    truck_length: "8.5m",
    truck_capacity: "20 Tons",
    created_at: "2024-03-05T09:00:00Z",
    registration_status: "MSS_VERIFIED",
    registered_by: { company_name: "Dangote Transport Services", user_account: "Sule Musa" },
    visibility: "PUBLIC",
    truck_status: "ON_TRIP",
    mss_verification_number: "MSS-2024-005678",
    verification_timestamp: "2024-03-10T11:00:00Z",
    rfid_tag_number: "RFID-ETSS-005678",
  },
  {
    id: "trk-003",
    plate_number: "LND-501-KJ",
    truck_type: "FLATBED",
    color: "Blue",
    chassis_number: "YV2RT40A8FB345678",
    brand: "Volvo",
    model: "FH16 750",
    truck_length: "13.6m",
    truck_capacity: "35 Tons",
    created_at: "2024-01-20T08:00:00Z",
    registration_status: "MSS_VERIFIED",
    registered_by: { company_name: "BUA Transport Services", user_account: "Amina Suleiman" },
    visibility: "PRIVATE",
    truck_status: "IN_FACILITY",
    mss_verification_number: "MSS-2024-009012",
    verification_timestamp: "2024-01-25T14:00:00Z",
    rfid_tag_number: "RFID-ETSS-009012",
  },
  {
    id: "trk-004",
    plate_number: "ABJ-872-FG",
    truck_type: "40-FOOTER",
    color: "Grey",
    chassis_number: "XLRTGK00005456789",
    brand: "DAF",
    model: "CF 85.510",
    truck_length: "12.2m",
    truck_capacity: "40 Tons",
    created_at: "2024-04-12T09:00:00Z",
    registration_status: "MSS_VERIFIED",
    registered_by: { company_name: "Mikano Logistics", user_account: "Chukwudi Nwosu" },
    visibility: "PUBLIC",
    truck_status: "AVAILABLE",
    mss_verification_number: "MSS-2024-003456",
    mss_expiry_date: "2025-12-31T00:00:00Z",
    verification_timestamp: "2024-04-18T10:00:00Z",
    rfid_tag_number: "RFID-ETSS-003456",
  },
  {
    id: "trk-005",
    plate_number: "KAN-256-NA",
    truck_type: "TANKER",
    color: "Green",
    chassis_number: "YS2R4X20001567890",
    brand: "Scania",
    model: "R 500 LA",
    truck_length: "10.5m",
    truck_capacity: "30,000 Litres",
    created_at: "2024-02-28T10:00:00Z",
    registration_status: "MSS_VERIFIED",
    registered_by: { company_name: "ABC Logistics Ltd", user_account: "Emeka Okafor" },
    visibility: "PUBLIC",
    truck_status: "MATCHED",
    mss_verification_number: "MSS-2024-007890",
    verification_timestamp: "2024-03-05T09:00:00Z",
    rfid_tag_number: "RFID-ETSS-007890",
  },
  {
    id: "trk-006",
    plate_number: "OGS-789-LA",
    truck_type: "20-FOOTER",
    color: "White",
    chassis_number: "ZCFC74BA8EF678901",
    brand: "Iveco",
    model: "Stralis 560",
    truck_length: "8.0m",
    truck_capacity: "20 Tons",
    created_at: "2024-03-22T08:00:00Z",
    registration_status: "MSS_VERIFIED",
    registered_by: { company_name: "Coscharis Transport", user_account: "Folake Adeyemi" },
    visibility: "PUBLIC",
    truck_status: "IN_PREGATE",
    mss_verification_number: "MSS-2024-002345",
    verification_timestamp: "2024-03-28T11:00:00Z",
    rfid_tag_number: "RFID-ETSS-002345",
  },
  {
    id: "trk-007",
    plate_number: "IMO-312-ZD",
    truck_type: "LOW_LOADER",
    color: "Yellow",
    chassis_number: "WDB9300341L789012",
    brand: "Mercedes-Benz",
    model: "Actros 3358 S",
    truck_length: "16.5m",
    truck_capacity: "60 Tons",
    created_at: "2024-01-08T09:00:00Z",
    registration_status: "MSS_VERIFIED",
    registered_by: { company_name: "Stallion Group Transport", user_account: "Usman Bello" },
    visibility: "PRIVATE",
    truck_status: "IN_TERMINAL",
    mss_verification_number: "MSS-2024-006789",
    verification_timestamp: "2024-01-14T10:00:00Z",
    rfid_tag_number: "RFID-ETSS-006789",
  },
  {
    id: "trk-008",
    plate_number: "RIV-944-PH",
    truck_type: "40-FOOTER",
    color: "Blue",
    chassis_number: "WMA06XZZ8NM890123",
    brand: "MAN",
    model: "TGS 26.440",
    truck_length: "12.2m",
    truck_capacity: "40 Tons",
    created_at: "2024-05-01T08:00:00Z",
    registration_status: "MSS_VERIFIED",
    registered_by: { company_name: "Spedag Intermodal Nigeria", user_account: "Ngozi Eze" },
    visibility: "PUBLIC",
    truck_status: "GTG_FACILITY",
    mss_verification_number: "MSS-2024-010112",
    verification_timestamp: "2024-05-08T14:00:00Z",
    rfid_tag_number: "RFID-ETSS-010112",
  },
  {
    id: "trk-009",
    plate_number: "LAG-777-AA",
    truck_type: "FLATBED",
    color: "Silver",
    chassis_number: "YV2RT40A8FB901234",
    brand: "Volvo",
    model: "FM 460",
    truck_length: "13.6m",
    truck_capacity: "32 Tons",
    created_at: "2024-03-18T10:00:00Z",
    registration_status: "MSS_VERIFIED",
    registered_by: { company_name: "ABC Logistics Ltd", user_account: "Emeka Okafor" },
    visibility: "PUBLIC",
    truck_status: "LEFT_TERMINAL",
    mss_verification_number: "MSS-2024-004321",
    verification_timestamp: "2024-03-25T11:00:00Z",
    rfid_tag_number: "RFID-ETSS-004321",
  },
  {
    id: "trk-010",
    plate_number: "EKO-555-BK",
    truck_type: "20-FOOTER",
    color: "Black",
    chassis_number: "XLRTGK00005012345",
    brand: "DAF",
    model: "CF 85.360",
    truck_length: "8.5m",
    truck_capacity: "20 Tons",
    created_at: "2024-04-25T09:00:00Z",
    registration_status: "MSS_VERIFIED",
    registered_by: { company_name: "Dangote Transport Services", user_account: "Ibrahim Aliyu" },
    visibility: "PRIVATE",
    truck_status: "AVAILABLE",
    mss_verification_number: "MSS-2024-008765",
    verification_timestamp: "2024-05-02T10:00:00Z",
    rfid_tag_number: "RFID-ETSS-008765",
  },

  // ── Unverified ──
  {
    id: "trk-011",
    plate_number: "LGS-100-CD",
    truck_type: "20-FOOTER",
    color: "White",
    chassis_number: "WMA06XZZ8NM111111",
    brand: "MAN",
    model: "TGX 18.440",
    truck_length: "8.5m",
    truck_capacity: "20 Tons",
    created_at: "2026-03-10T08:00:00Z",
    registration_status: "UNVERIFIED",
    registered_by: { company_name: "BUA Transport Services", user_account: "Amina Suleiman" },
    visibility: "PUBLIC",
  },
  {
    id: "trk-012",
    plate_number: "ABU-200-EF",
    truck_type: "FLATBED",
    color: "Red",
    chassis_number: "WDB9300341L222222",
    brand: "Mercedes-Benz",
    model: "Actros 2645",
    truck_length: "13.6m",
    truck_capacity: "30 Tons",
    created_at: "2026-03-18T09:00:00Z",
    registration_status: "UNVERIFIED",
    registered_by: { company_name: "Mikano Logistics", user_account: "Chukwudi Nwosu" },
    visibility: "PRIVATE",
  },
  {
    id: "trk-013",
    plate_number: "PHC-300-GH",
    truck_type: "40-FOOTER",
    color: "Blue",
    chassis_number: "YS2R4X20001333333",
    brand: "Scania",
    model: "R 450 LA",
    truck_length: "12.2m",
    truck_capacity: "40 Tons",
    created_at: "2026-03-25T08:00:00Z",
    registration_status: "VERIFICATION_REQUESTED",
    registered_by: { company_name: "ABC Logistics Ltd", user_account: "Emeka Okafor" },
    visibility: "PUBLIC",
    mss_verification_number: "PENDING",
  },
  {
    id: "trk-014",
    plate_number: "KAN-400-IJ",
    truck_type: "TANKER",
    color: "Green",
    chassis_number: "ZCFC74BA8EF444444",
    brand: "Iveco",
    model: "Trakker 500",
    truck_length: "10.5m",
    truck_capacity: "28,000 Litres",
    created_at: "2026-04-02T09:00:00Z",
    registration_status: "UNVERIFIED",
    registered_by: { company_name: "Coscharis Transport", user_account: "Folake Adeyemi" },
    visibility: "PUBLIC",
  },
  {
    id: "trk-015",
    plate_number: "ABI-500-KL",
    truck_type: "LOW_LOADER",
    color: "Grey",
    chassis_number: "XLRTGK00005555555",
    brand: "DAF",
    model: "XF 530",
    truck_length: "16.0m",
    truck_capacity: "55 Tons",
    created_at: "2026-04-08T08:00:00Z",
    registration_status: "UNVERIFIED",
    registered_by: { company_name: "Stallion Group Transport", user_account: "Usman Bello" },
    visibility: "PRIVATE",
  },
  {
    id: "trk-016",
    plate_number: "ENU-600-MN",
    truck_type: "20-FOOTER",
    color: "Yellow",
    chassis_number: "YV2RT40A8FB666666",
    brand: "Volvo",
    model: "FMX 420",
    truck_length: "8.0m",
    truck_capacity: "18 Tons",
    created_at: "2026-04-15T09:00:00Z",
    registration_status: "UNVERIFIED",
    registered_by: { company_name: "Spedag Intermodal Nigeria", user_account: "Ngozi Eze" },
    visibility: "PUBLIC",
  },

  // ── Flagged (unpaid penalties) ──
  {
    id: "trk-017",
    plate_number: "TRP-221-LG",
    truck_type: "40-FOOTER",
    color: "White",
    chassis_number: "WDB9300341L777777",
    brand: "Mercedes-Benz",
    model: "Actros 2548",
    truck_length: "12.2m",
    truck_capacity: "40 Tons",
    created_at: "2024-06-01T08:00:00Z",
    registration_status: "FLAGGED",
    registered_by: { company_name: "ABC Logistics Ltd", user_account: "Emeka Okafor" },
    visibility: "PUBLIC",
    mss_verification_number: "MSS-2024-021001",
    penalty: {
      penalty_id: "PEN-2026-00117",
      penalty_type: "OVERSTAY",
      amount: 50000,
      date_issued: "2026-04-10T14:30:00Z",
      issued_by: "Okonkwo Samuel (EO-001)",
      payment_status: "UNPAID",
      booked_by: { company_name: "ABC Logistics Ltd", user_account: "Emeka Okafor" },
    },
  },
  {
    id: "trk-018",
    plate_number: "BDG-335-KJ",
    truck_type: "20-FOOTER",
    color: "Red",
    chassis_number: "WMA06XZZ8NM888888",
    brand: "MAN",
    model: "TGX 26.480",
    truck_length: "8.5m",
    truck_capacity: "20 Tons",
    created_at: "2024-07-15T09:00:00Z",
    registration_status: "FLAGGED",
    registered_by: { company_name: "Dangote Transport Services", user_account: "Sule Musa" },
    visibility: "PUBLIC",
    mss_verification_number: "MSS-2024-021002",
    penalty: {
      penalty_id: "PEN-2026-00218",
      penalty_type: "ROUTE_VIOLATION",
      amount: 30000,
      date_issued: "2026-04-15T09:15:00Z",
      issued_by: "Adeyemi Fatima (EO-002)",
      payment_status: "DISPUTED",
      booked_by: { company_name: "Dangote Transport Services", user_account: "Sule Musa" },
    },
  },
  {
    id: "trk-019",
    plate_number: "APT-119-AB",
    truck_type: "TANKER",
    color: "Grey",
    chassis_number: "YS2R4X20001999999",
    brand: "Scania",
    model: "R 500 LA",
    truck_length: "10.5m",
    truck_capacity: "30,000 Litres",
    created_at: "2024-05-20T10:00:00Z",
    registration_status: "FLAGGED",
    registered_by: { company_name: "BUA Transport Services", user_account: "Amina Suleiman" },
    visibility: "PRIVATE",
    mss_verification_number: "MSS-2024-021003",
    penalty: {
      penalty_id: "PEN-2026-00319",
      penalty_type: "UNAUTHORIZED_PARKING",
      amount: 20000,
      date_issued: "2026-04-18T16:00:00Z",
      issued_by: "Okonkwo Samuel (EO-001)",
      payment_status: "UNPAID",
      booked_by: { company_name: "BUA Transport Services", user_account: "Amina Suleiman" },
    },
  },
  {
    id: "trk-020",
    plate_number: "NKK-782-OG",
    truck_type: "FLATBED",
    color: "Blue",
    chassis_number: "YV2RT40A8FB100001",
    brand: "Volvo",
    model: "FH16 750",
    truck_length: "13.6m",
    truck_capacity: "35 Tons",
    created_at: "2024-08-10T08:00:00Z",
    registration_status: "FLAGGED",
    registered_by: { company_name: "Mikano Logistics", user_account: "Chukwudi Nwosu" },
    visibility: "PUBLIC",
    mss_verification_number: "MSS-2024-021004",
    penalty: {
      penalty_id: "PEN-2026-00420",
      penalty_type: "OVERWEIGHT",
      amount: 75000,
      date_issued: "2026-04-20T11:00:00Z",
      issued_by: "Ibrahim Musa (EO-003)",
      payment_status: "UNPAID",
      booked_by: { company_name: "Mikano Logistics", user_account: "Chukwudi Nwosu" },
    },
  },
  {
    id: "trk-021",
    plate_number: "CAD-448-IM",
    truck_type: "40-FOOTER",
    color: "Black",
    chassis_number: "XLRTGK00005100002",
    brand: "DAF",
    model: "CF 85.510",
    truck_length: "12.2m",
    truck_capacity: "40 Tons",
    created_at: "2024-09-05T09:00:00Z",
    registration_status: "FLAGGED",
    registered_by: { company_name: "Coscharis Transport", user_account: "Folake Adeyemi" },
    visibility: "PUBLIC",
    mss_verification_number: "MSS-2024-021005",
    penalty: {
      penalty_id: "PEN-2026-00521",
      penalty_type: "OVERSTAY",
      amount: 50000,
      date_issued: "2026-04-22T13:45:00Z",
      issued_by: "Adeyemi Fatima (EO-002)",
      payment_status: "PAID",
      booked_by: { company_name: "Coscharis Transport", user_account: "Folake Adeyemi" },
    },
  },

  // ── Disabled ──
  {
    id: "trk-022",
    plate_number: "LND-881-ZX",
    truck_type: "40-FOOTER",
    color: "White",
    chassis_number: "WDB9300341L200001",
    brand: "Mercedes-Benz",
    model: "Actros 2548",
    truck_length: "12.2m",
    truck_capacity: "40 Tons",
    created_at: "2023-11-10T08:00:00Z",
    registration_status: "DISABLED",
    registered_by: { company_name: "Stallion Group Transport", user_account: "Usman Bello" },
    visibility: "PUBLIC",
    mss_verification_number: "MSS-2023-088001",
    verification_timestamp: "2023-11-18T10:00:00Z",
    disable_info: {
      disabled_by: "NPA — Uche Obi (NPA-022)",
      disable_reason: "Expired vehicle particulars and insurance documents",
      disable_timestamp: "2026-02-15T11:00:00Z",
    },
  },
  {
    id: "trk-023",
    plate_number: "ABJ-553-FG",
    truck_type: "20-FOOTER",
    color: "Red",
    chassis_number: "WMA06XZZ8NM200002",
    brand: "MAN",
    model: "TGX 18.440",
    truck_length: "8.5m",
    truck_capacity: "20 Tons",
    created_at: "2023-12-05T09:00:00Z",
    registration_status: "DISABLED",
    registered_by: { company_name: "Spedag Intermodal Nigeria", user_account: "Ngozi Eze" },
    visibility: "PRIVATE",
    mss_verification_number: "MSS-2023-099002",
    verification_timestamp: "2023-12-12T14:00:00Z",
    disable_info: {
      disabled_by: "SuperAdmin — Adewale Peters (SA-001)",
      disable_reason: "Multiple compliance violations recorded in Q1 2026",
      disable_timestamp: "2026-03-01T09:30:00Z",
    },
  },
  {
    id: "trk-024",
    plate_number: "KAN-227-NA",
    truck_type: "TANKER",
    color: "Blue",
    chassis_number: "YS2R4X20001200003",
    brand: "Scania",
    model: "G 480 LA",
    truck_length: "10.5m",
    truck_capacity: "28,000 Litres",
    created_at: "2024-01-15T08:00:00Z",
    registration_status: "DISABLED",
    registered_by: { company_name: "ABC Logistics Ltd", user_account: "Emeka Okafor" },
    visibility: "PUBLIC",
    mss_verification_number: "MSS-2024-011003",
    verification_timestamp: "2024-01-22T11:00:00Z",
    disable_info: {
      disabled_by: "NPA — Uche Obi (NPA-022)",
      disable_reason: "Safety inspection failure — brake system defects",
      disable_timestamp: "2026-03-20T14:00:00Z",
    },
  },
  {
    id: "trk-025",
    plate_number: "OGS-994-LA",
    truck_type: "FLATBED",
    color: "Grey",
    chassis_number: "YV2RT40A8FB200004",
    brand: "Volvo",
    model: "FM 500",
    truck_length: "13.6m",
    truck_capacity: "30 Tons",
    created_at: "2024-02-20T09:00:00Z",
    registration_status: "DISABLED",
    registered_by: { company_name: "BUA Transport Services", user_account: "Amina Suleiman" },
    visibility: "PRIVATE",
    mss_verification_number: "MSS-2024-012004",
    verification_timestamp: "2024-02-28T10:00:00Z",
    disable_info: {
      disabled_by: "NPA — Fatima Yusuf (NPA-045)",
      disable_reason: "Overdue routine maintenance — overdue by 90 days",
      disable_timestamp: "2026-04-05T10:30:00Z",
    },
  },
];

// ─── Derived Summary ───
function isTruckMssExpired(truck: Truck): boolean {
  if (!truck.mss_expiry_date) return false;
  return new Date(truck.mss_expiry_date) < new Date();
}

export function buildTrucksSummary(trucks: Truck[]): TrucksSummary {
  const verifiedTrucks = trucks.filter((t) => t.registration_status === "MSS_VERIFIED");
  return {
    total: trucks.length,
    mss_verified: verifiedTrucks.filter((t) => !isTruckMssExpired(t)).length,
    mss_expired: verifiedTrucks.filter((t) => isTruckMssExpired(t)).length,
    unverified: trucks.filter((t) => t.registration_status === "UNVERIFIED").length,
    verification_requested: trucks.filter((t) => t.registration_status === "VERIFICATION_REQUESTED").length,
    flagged: trucks.filter((t) => t.registration_status === "FLAGGED").length,
    disabled: trucks.filter((t) => t.registration_status === "DISABLED").length,
    archived: trucks.filter((t) => t.registration_status === "ARCHIVED").length,
    available: trucks.filter((t) => t.truck_status === "AVAILABLE").length,
    on_trip: trucks.filter((t) => t.truck_status === "ON_TRIP").length,
  };
}
