import type {
  UtilityTicket,
  UtilityTicketsSummary,
} from "@/types/utility-tickets.types";

export const MOCK_UTILITY_TICKETS: UtilityTicket[] = [
  {
    id: "ut-001",
    ticket_id: "UT-2026-004821",
    terminal: {
      id: "term-apt",
      name: "Apapa Port Terminal A",
      code: "APT-A",
      type: "PORT",
      location: "Apapa, Lagos",
    },
    request_type: "POWER",
    description: "Emergency generator fuel supply required for cold storage unit.",
    full_description:
      "Emergency generator fuel supply required for cold storage unit at Berth 3. Cold chain containers arriving on MV Atlantic Star require uninterrupted power. Estimated 500 litres diesel needed within 4 hours.",
    status: "PENDING",
    booking_priority: "PRIORITY",
    delivery_company_name: "PowerServe Nigeria Ltd",
    truck_plate_number: "LAG-887-KJA",
    date_raised: "2026-07-11T08:15:00.000Z",
    last_updated_at: "2026-07-11T08:15:00.000Z",
    raised_by: { user_id: "usr-201", user_name: "Emeka Okafor" },
    super_admin_approved: false,
    request_history: [
      {
        id: "h-001",
        status: "PENDING",
        timestamp: "2026-07-11T08:15:00.000Z",
        performed_by: "Emeka Okafor",
        notes: "Utility ticket raised by terminal operator.",
      },
    ],
    e_ticket_available: false,
  },
  {
    id: "ut-002",
    ticket_id: "UT-2026-004815",
    terminal: {
      id: "term-tic",
      name: "Tincan Island Terminal",
      code: "TIC-01",
      type: "PORT",
      location: "Tincan Island, Lagos",
    },
    request_type: "WATER",
    description: "Potable water tanker delivery for vessel sanitation.",
    full_description:
      "Potable water tanker delivery required for vessel sanitation on MV Pacific Dawn. 10,000 litres needed. Delivery company will use unregistered tanker LAG-442-BND.",
    status: "IN_PROGRESS",
    booking_priority: "PRIORITY",
    delivery_company_name: "AquaFlow Services",
    truck_plate_number: "LAG-442-BND",
    date_raised: "2026-07-10T14:30:00.000Z",
    last_updated_at: "2026-07-11T06:00:00.000Z",
    raised_by: { user_id: "usr-205", user_name: "Amina Suleiman" },
    super_admin_approved: true,
    approved_by: "Femi Okunlola",
    approved_at: "2026-07-10T16:00:00.000Z",
    assigned_personnel: [
      {
        id: "pers-01",
        name: "Samuel Okonkwo",
        role: "Utility Coordinator",
        assigned_at: "2026-07-10T16:05:00.000Z",
      },
    ],
    request_history: [
      {
        id: "h-002a",
        status: "PENDING",
        timestamp: "2026-07-10T14:30:00.000Z",
        performed_by: "Amina Suleiman",
        notes: "Utility ticket raised.",
      },
      {
        id: "h-002b",
        status: "IN_PROGRESS",
        timestamp: "2026-07-10T16:05:00.000Z",
        performed_by: "Femi Okunlola",
        notes: "Approved by SuperAdmin. Assigned to utility coordinator.",
      },
    ],
    e_ticket_available: true,
  },
  {
    id: "ut-003",
    ticket_id: "UT-2026-004798",
    terminal: {
      id: "term-cbr",
      name: "Calabar Non-Port Terminal",
      code: "CBR-NPT",
      type: "NON_PORT",
      location: "Calabar, Cross River",
    },
    request_type: "MAINTENANCE",
    description: "Crane hydraulic system repair — spare parts delivery.",
    full_description:
      "Crane hydraulic system repair requires delivery of spare parts (hydraulic hoses and seals). Delivery company: MechParts West Africa. Truck plate: CRS-901-XK (not registered on ETSS).",
    status: "RESOLVED",
    booking_priority: "STANDARD",
    delivery_company_name: "MechParts West Africa",
    truck_plate_number: "CRS-901-XK",
    date_raised: "2026-07-08T09:00:00.000Z",
    last_updated_at: "2026-07-09T17:30:00.000Z",
    raised_by: { user_id: "usr-310", user_name: "Sule Musa" },
    super_admin_approved: true,
    approved_by: "Femi Okunlola",
    approved_at: "2026-07-08T11:00:00.000Z",
    assigned_personnel: [
      {
        id: "pers-02",
        name: "Grace Etim",
        role: "Maintenance Supervisor",
        assigned_at: "2026-07-08T11:15:00.000Z",
      },
    ],
    request_history: [
      {
        id: "h-003a",
        status: "PENDING",
        timestamp: "2026-07-08T09:00:00.000Z",
        performed_by: "Sule Musa",
        notes: "Ticket raised.",
      },
      {
        id: "h-003b",
        status: "IN_PROGRESS",
        timestamp: "2026-07-08T11:15:00.000Z",
        performed_by: "Femi Okunlola",
        notes: "Approved and assigned.",
      },
      {
        id: "h-003c",
        status: "RESOLVED",
        timestamp: "2026-07-09T17:30:00.000Z",
        performed_by: "Grace Etim",
        notes: "Parts delivered and crane restored to operation.",
      },
    ],
    e_ticket_available: true,
  },
  {
    id: "ut-004",
    ticket_id: "UT-2026-004802",
    terminal: {
      id: "term-onn",
      name: "Onne Port Terminal",
      code: "ONN-02",
      type: "PORT",
      location: "Onne, Rivers",
    },
    request_type: "WASTE_MANAGEMENT",
    description: "Hazardous waste collection from berth area.",
    full_description:
      "Hazardous waste collection from berth area following container inspection. EcoWaste Solutions to dispatch certified collection vehicle.",
    status: "CLOSED",
    booking_priority: "PRIORITY",
    delivery_company_name: "EcoWaste Solutions",
    date_raised: "2026-07-05T07:00:00.000Z",
    last_updated_at: "2026-07-06T12:00:00.000Z",
    raised_by: { user_id: "usr-220", user_name: "Chukwudi Nwosu" },
    super_admin_approved: true,
    approved_by: "Femi Okunlola",
    approved_at: "2026-07-05T09:00:00.000Z",
    assigned_personnel: [
      {
        id: "pers-03",
        name: "Ibrahim Bello",
        role: "Environmental Officer",
        assigned_at: "2026-07-05T09:30:00.000Z",
      },
    ],
    request_history: [
      {
        id: "h-004a",
        status: "PENDING",
        timestamp: "2026-07-05T07:00:00.000Z",
        performed_by: "Chukwudi Nwosu",
        notes: "Ticket raised.",
      },
      {
        id: "h-004b",
        status: "IN_PROGRESS",
        timestamp: "2026-07-05T09:30:00.000Z",
        performed_by: "Femi Okunlola",
        notes: "Approved — priority booking.",
      },
      {
        id: "h-004c",
        status: "RESOLVED",
        timestamp: "2026-07-06T10:00:00.000Z",
        performed_by: "Ibrahim Bello",
        notes: "Waste collected and manifest filed.",
      },
      {
        id: "h-004d",
        status: "CLOSED",
        timestamp: "2026-07-06T12:00:00.000Z",
        performed_by: "Femi Okunlola",
        notes: "Ticket closed after verification.",
      },
    ],
    e_ticket_available: true,
  },
  {
    id: "ut-005",
    ticket_id: "UT-2026-004833",
    terminal: {
      id: "term-wri",
      name: "Warri Bonded Terminal",
      code: "WRI-BT",
      type: "NON_PORT",
      location: "Warri, Delta",
    },
    request_type: "SECURITY",
    description: "Additional security personnel deployment for cargo inspection.",
    full_description:
      "Additional security personnel deployment requested for extended cargo inspection operations over the weekend. SecureGuard Nigeria to provide 4 personnel.",
    status: "PENDING",
    booking_priority: "STANDARD",
    delivery_company_name: "SecureGuard Nigeria",
    date_raised: "2026-07-11T10:45:00.000Z",
    last_updated_at: "2026-07-11T10:45:00.000Z",
    raised_by: { user_id: "usr-330", user_name: "Fatima Abdullahi" },
    super_admin_approved: false,
    request_history: [
      {
        id: "h-005",
        status: "PENDING",
        timestamp: "2026-07-11T10:45:00.000Z",
        performed_by: "Fatima Abdullahi",
        notes: "Utility ticket raised.",
      },
    ],
    e_ticket_available: false,
  },
  {
    id: "ut-006",
    ticket_id: "UT-2026-004819",
    terminal: {
      id: "term-lds",
      name: "Lekki Deep Sea Terminal",
      code: "LDS-01",
      type: "PORT",
      location: "Lekki, Lagos",
    },
    request_type: "FUEL",
    description: "Diesel delivery for terminal yard equipment.",
    full_description:
      "Diesel delivery for terminal yard equipment — 2,000 litres required for reach stackers and forklifts. PetroLink Logistics handling delivery via LAG-556-MNP.",
    status: "IN_PROGRESS",
    booking_priority: "PRIORITY",
    delivery_company_name: "PetroLink Logistics",
    truck_plate_number: "LAG-556-MNP",
    date_raised: "2026-07-09T11:20:00.000Z",
    last_updated_at: "2026-07-10T08:00:00.000Z",
    raised_by: { user_id: "usr-215", user_name: "David Adeyemi" },
    super_admin_approved: true,
    approved_by: "Femi Okunlola",
    approved_at: "2026-07-09T13:00:00.000Z",
    assigned_personnel: [
      {
        id: "pers-04",
        name: "Michael Osei",
        role: "Operations Lead",
        assigned_at: "2026-07-09T13:10:00.000Z",
      },
    ],
    request_history: [
      {
        id: "h-006a",
        status: "PENDING",
        timestamp: "2026-07-09T11:20:00.000Z",
        performed_by: "David Adeyemi",
        notes: "Ticket raised.",
      },
      {
        id: "h-006b",
        status: "IN_PROGRESS",
        timestamp: "2026-07-09T13:10:00.000Z",
        performed_by: "Femi Okunlola",
        notes: "Approved — priority utility booking.",
      },
    ],
    e_ticket_available: true,
  },
];

export const RAISED_BY_OPTIONS = [
  "All",
  ...Array.from(new Set(MOCK_UTILITY_TICKETS.map((t) => t.raised_by.user_name))),
];

export function buildUtilityTicketsSummary(tickets: UtilityTicket[]): UtilityTicketsSummary {
  return {
    total: tickets.length,
    pending: tickets.filter((t) => t.status === "PENDING").length,
    in_progress: tickets.filter((t) => t.status === "IN_PROGRESS").length,
    resolved: tickets.filter((t) => t.status === "RESOLVED").length,
    closed: tickets.filter((t) => t.status === "CLOSED").length,
    port_terminals: tickets.filter((t) => t.terminal.type === "PORT").length,
    non_port_terminals: tickets.filter((t) => t.terminal.type === "NON_PORT").length,
  };
}
